/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Top7RouteImport } from './routes/top-7'
import { Route as JoyasOcultasRouteImport } from './routes/joyas-ocultas'
import { Route as GenerosRouteImport } from './routes/generos'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AnimesTipoRouteImport } from './routes/animes-tipo'
import { Route as AnimesCortosRouteImport } from './routes/animes-cortos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const Top7Route = Top7RouteImport.update({
  id: '/top-7',
  path: '/top-7',
  getParentRoute: () => rootRouteImport,
} as any)
const JoyasOcultasRoute = JoyasOcultasRouteImport.update({
  id: '/joyas-ocultas',
  path: '/joyas-ocultas',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerosRoute = GenerosRouteImport.update({
  id: '/generos',
  path: '/generos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimesTipoRoute = AnimesTipoRouteImport.update({
  id: '/animes-tipo',
  path: '/animes-tipo',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimesCortosRoute = AnimesCortosRouteImport.update({
  id: '/animes-cortos',
  path: '/animes-cortos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animes-cortos': typeof AnimesCortosRoute
  '/animes-tipo': typeof AnimesTipoRoute
  '/blog': typeof BlogRouteWithChildren
  '/faq': typeof FaqRoute
  '/generos': typeof GenerosRoute
  '/joyas-ocultas': typeof JoyasOcultasRoute
  '/top-7': typeof Top7Route
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animes-cortos': typeof AnimesCortosRoute
  '/animes-tipo': typeof AnimesTipoRoute
  '/blog': typeof BlogRouteWithChildren
  '/faq': typeof FaqRoute
  '/generos': typeof GenerosRoute
  '/joyas-ocultas': typeof JoyasOcultasRoute
  '/top-7': typeof Top7Route
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animes-cortos': typeof AnimesCortosRoute
  '/animes-tipo': typeof AnimesTipoRoute
  '/blog': typeof BlogRouteWithChildren
  '/faq': typeof FaqRoute
  '/generos': typeof GenerosRoute
  '/joyas-ocultas': typeof JoyasOcultasRoute
  '/top-7': typeof Top7Route
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/animes-cortos'
    | '/animes-tipo'
    | '/blog'
    | '/faq'
    | '/generos'
    | '/joyas-ocultas'
    | '/top-7'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/animes-cortos'
    | '/animes-tipo'
    | '/blog'
    | '/faq'
    | '/generos'
    | '/joyas-ocultas'
    | '/top-7'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/animes-cortos'
    | '/animes-tipo'
    | '/blog'
    | '/faq'
    | '/generos'
    | '/joyas-ocultas'
    | '/top-7'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimesCortosRoute: typeof AnimesCortosRoute
  AnimesTipoRoute: typeof AnimesTipoRoute
  BlogRoute: typeof BlogRouteWithChildren
  FaqRoute: typeof FaqRoute
  GenerosRoute: typeof GenerosRoute
  JoyasOcultasRoute: typeof JoyasOcultasRoute
  Top7Route: typeof Top7Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/top-7': {
      id: '/top-7'
      path: '/top-7'
      fullPath: '/top-7'
      preLoaderRoute: typeof Top7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joyas-ocultas': {
      id: '/joyas-ocultas'
      path: '/joyas-ocultas'
      fullPath: '/joyas-ocultas'
      preLoaderRoute: typeof JoyasOcultasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generos': {
      id: '/generos'
      path: '/generos'
      fullPath: '/generos'
      preLoaderRoute: typeof GenerosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animes-tipo': {
      id: '/animes-tipo'
      path: '/animes-tipo'
      fullPath: '/animes-tipo'
      preLoaderRoute: typeof AnimesTipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animes-cortos': {
      id: '/animes-cortos'
      path: '/animes-cortos'
      fullPath: '/animes-cortos'
      preLoaderRoute: typeof AnimesCortosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimesCortosRoute: AnimesCortosRoute,
  AnimesTipoRoute: AnimesTipoRoute,
  BlogRoute: BlogRouteWithChildren,
  FaqRoute: FaqRoute,
  GenerosRoute: GenerosRoute,
  JoyasOcultasRoute: JoyasOcultasRoute,
  Top7Route: Top7Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
